Resources:

# Create a iam group
  IAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: CloudSpace-Engineers-Panther
      ManagedPolicyArns:
        - !Ref IAMPolicy

# Create a iam user
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - CloudSpace-Engineers-Panther
      UserName: Panther
      LoginProfile:
        Password: xxxxxxx
        PasswordResetRequired: true

# Create a manage policy
  IAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: full-admin-access-except-billing
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Action:
              - billing:*
            Resource: "*"
          - Effect: Allow
            Action: "*"
            Resource: "*"

# Assign a user to the group
  IAMUserGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: CloudSpace-Engineers-Panther
      Users:
        - !Ref IAMUser


# Create an iam group
  IAMGroup2:
    Type: AWS::IAM::Group
    Properties:
      GroupName: NAS-Financial-Group-Security-Team
      ManagedPolicyArns:
        - !Ref IAMPolicy2


# Create a iam user
  IAMUser2:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - NAS-Financial-Group-Security-Team
      UserName: Security-Team
      LoginProfile:
        Password: xxxxxx
        PasswordResetRequired: true

# Create a manage policy
  IAMPolicy2:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: full-admin-access-with-billing
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"

# Assign a user to the group
  IAMUserGroup2:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: NAS-Financial-Group-Security-Team
      Users:
        - !Ref IAMUser2


# Create an iam group
  IAMGroup3:
    Type: AWS::IAM::Group
    Properties:
      GroupName: NAS-Financial-Group-Operations-Team
      ManagedPolicyArns:
        - !Ref IAMPolicy3

# Create a iam user
  IAMUser3:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - NAS-Financial-Group-Operations-Team
      UserName: Operations-Team
      LoginProfile:
        Password: xxxxxxx
        PasswordResetRequired: true

# Create a manage policy
  IAMPolicy3:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: full-admin-access-to-deploy-ONLY-in-the-us-east-1-region
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
            Condition:
              StringEquals:
                aws:RequestedRegion: us-east-1

# Assign a user to the group
  IAMUserGroup3:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: NAS-Financial-Group-Operations-Team
      Users:
        - !Ref IAMUser3

